job('First-Maven-Project-Via-DSC') { 
	description("First Maven job generated by the DSL on ${new Date()}, Maven project hosted on github")
	scm {
		git {
          		remote {
            			url("https://github.com/ucodes/Maven-Simple.git")
          	}
          		branch('master')
        	}
	}
	triggers { 
		scm('* * * * *')
	} 
	steps { 
		maven('clean package', './pom.xml') 
	}
	publishers { 
		//archive the war file generated
		archiveArtifacts '**/*.jar' 
	} 
}
